steps:
- name: gcr.io/cloud-builders/docker
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/codedx-api-wrapper', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'run', 'gcr.io/$PROJECT_ID/codedx-api-wrapper', 'download_pdf_report.py', 'test-api', 'test-project' ]
images:
- 'gcr.io/$PROJECT_ID/codedx-api-wrapper'