from apiclient.apiclient import APIClient
import json
import re

# Projects Client for Code DX Projects API
class Users(APIClient):
	
	def __init__(self, base, api_key, verbose = False):
		""" Creates an API Client for Code DX Users API
				base: String representing base url from Code DX
				api_key: String representing API key from Code DX
				verbose: Boolean - not supported yet

		"""
		super().__init__(base, api_key, verbose)
		self.user_types = {'Local': 'local', 'LDAP': 'ldap', 'External': 'external', 'Key': 'key'}

	def create_user(self, name, pw, enabled, user_type):
		""" Creates a user based on given user type.
		"""
		if user_type not in self.user_types:
			raise Exception("Not a valid user_type.")
		local_url = '/api/admin/users/%s' % self.user_types[user_type]
		self.type_check(name, str, "Username")
		self.type_check(pw, str, "Password")
		self.type_check(enabled, bool, "Enabled")
		user = {'name': name, 'password': pw, 'enabled': enabled}
		params = {'user': user}
		res = self.call("POST", local_path=local_url, json=params)
		return res

	def get_users(self, user_type='All'):
		""" Returns a list of users with optional filter by type.
		"""
		if user_type not in self.user_types and user_type != 'All':
			raise Exception("Not a valid user_type.")
		if user_type in self.user_types:
			local_url = '/api/admin/users/%s' % self.user_types[user_type]
		else:
			local_url = '/api/admin/users'
		res = self.call("GET", local_path=local_url)
		return res

	def get_user(self, uid):
		users = self.get_users()
		for user in users:
			if user["id"] == uid:
				return user
		raise Exception("Not a valid User ID.")

	def create_local(self, name, pw, enabled):
		""" Creates a local user.
		"""
		return self.create_user(name, pw, enabled, 'Local')

	def get_locals(self):
		""" Gets local users.
		"""
		return self.get_users('Local')

	def create_ldap(self, name, pw, enabled):
		""" Creates a ldap user.
		"""
		return self.create_user(name, pw, enabled, 'LDAP')

	def get_ldaps(self):
		""" Gets ldap users.
		"""
		return self.get_users('LDAP')

	def create_external(self, name, pw, enabled):
		""" Creates an external user.
		"""
		return self.create_user(name, pw, enabled, 'External')

	def get_externals(self):
		""" Gets external users.
		"""
		return self.get_users('External')

	def create_key(self, name, pw, enabled):
		""" Creates an API key.
		"""
		return self.create_user(name, pw, enabled, 'Key')

	def get_keys(self):
		""" Gets API keys.
		"""
		return self.get_users('Key')

	def user_settings(self, uid, isEnabled, isAdmin):
		""" A single endpoint is shared by the “enable/disable user” and “add/remove admin role” functionality.
		"""
		self.type_check(isEnabled, bool, "isEnabled")
		self.type_check(isAdmin, bool, "isAdmin")
		self.type_check(uid, int, "User ID")
		local_url = '/api/admin/users/%d' % uid
		user_settings = {"isEnabled": isEnabled, "isAdmin": isAdmin}
		params = {'disableUser': user_settings}
		res = self.call("PUT", local_path=local_url, json=params)
		return res

	def enable_admin(self, uid):
		""" Gives admin privileges for the given user.
		"""
		user = self.get_user(uid)
		return self.user_settings(uid, user["isEnabled"], True)

	def disable_admin(self, uid):
		""" Removes admin privileges for the given user.
		"""
		user = self.get_user(uid)
		return self.user_settings(uid, user["isEnabled"], False)

	def enable_user(self, uid):
		""" Enables the given user.
		"""
		user = self.get_user(uid)
		return self.user_settings(uid, True, user["isAdmin"])

	def disable_user(self, uid):
		""" Disables the given user.
		"""
		user = self.get_user(uid)
		return self.user_settings(uid, False, user["isAdmin"])

	def delete_user(self, uid):
		""" To delete a user, you must know its id (found from its corresponding user object).
		"""
		self.type_check(uid, int, "User ID")
		local_url = '/api/admin/users/%d' % uid
		res = self.call("DELETE", local_path=local_url)
		return res

	def change_password(self, uid, pw):
		""" Local users’ passwords may be changed by administrators. Other user types don’t have passwords.
		"""
		self.type_check(uid, int, "User ID")
		self.type_check(pw, str, "New Password")
		params = {"password": pw}
		local_url = "/api/admin/users/local/%d/password" % uid
		res = self.call("POST", local_path=local_url, json=params, content_type=None)
		return res

	def regenerate_key(self, uid):
		""" API Keys are represented with the key user type. Their principal represents the actual key, and can be randomly regenerated by this endpoint. No request body is required.
		"""
		self.type_check(uid, int, "User ID")
		local_url = "/api/admin/users/key/%d/regenerate" % uid
		res = self.call("POST", local_path=local_url)
		return res